// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestInitialLoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }
  [Test]
  public void testInitialLogin() {
    driver.Navigate().GoToUrl("https://my.denovo.ua/");
    driver.Manage().Window.Size = new System.Drawing.Size(1521, 860);
    driver.FindElement(By.Id("inputUsername")).SendKeys("P.molodec.1@gmail.com");
    driver.FindElement(By.Id("inputPassword")).Click();
    driver.FindElement(By.Id("inputPassword")).SendKeys("Заказчик");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("inputCode")).SendKeys("4525");
    driver.FindElement(By.Id("MainHeaderSchemaCaptionValueLabel")).Click();
    var elements = driver.FindElements(By.Id("MainHeaderSchemaCaptionValueLabel"));
    Assert.True(elements.Count > 0);
    Assert.That(driver.FindElement(By.Id("MainHeaderSchemaCaptionValueLabel")).Text, Is.EqualTo("Головна сторінка"));
    driver.FindElement(By.CssSelector(".t-btn-style-green")).Click();
    var elements = driver.FindElements(By.LinkText("Створити заявку"));
    Assert.True(elements.Count > 0);
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.CssSelector(".header_item:nth-child(1) span")).Click();
    vars["win9918"] = waitForWindow(2000);
    driver.SwitchTo().Window(vars["win9918"].ToString());
    var elements = driver.FindElements(By.CssSelector(".face_title"));
    Assert.True(elements.Count > 0);
    Assert.That(driver.FindElement(By.CssSelector(".face_title")).Text, Is.EqualTo("ДОКУМЕНТАЦІЯ DE NOVO"));
    driver.FindElement(By.CssSelector(".btn")).Click();
  }
}
